name: Build and Deploy Locally (2 Stages)

on:
  push:
    branches:
      - master 

jobs:
  cleanup:
    name: Cleanup Old Images
    runs-on: self-hosted

    steps:
      - name: down old containers
        run: |
          sudo docker compose down
          sudo docker system prune -a
  build:
    name: Build Docker Images Locally
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images with Docker Compose
        run: sudo docker compose build

  deploy:
    name: Deploy Containers Locally
    runs-on: self-hosted

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare .env file
        run: |
          cp .env.copy .env 
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env

      - name: Start containers with Docker Compose
        run: sudo docker compose up -d

      - name: Optional - Prune old images
        run: sudo docker image prune -af
